--- !map:HashWithIndifferentAccess

default: &default
  host: server.fseconomy.net
  path: /data
  params: &params
    format: xml
    userkey: <%= ENV['FSE_ACCESS_KEY'] %>

aircrafts:
  <<: *default
  params:
    <<: *params
    query: aircraft
    search: makemodel

aircraft_models:
  <<: *default
  params:
    <<: *params
    query: aircraft
    search: configs
